### ISSUE TITLE
译文反馈

### ISSUE THREAD

**Issue by longqzh** [caicaishmily/pragmatic-programmer-zh#1]
这是少有的，让我觉得读译文比读原版更吃力的翻译。。。用机器译的吗？

**Comment by caicaishmily** [comment]
> 这是少有的，让我觉得读译文比读原版更吃力的翻译。。。用机器译的吗？

受限于水平，所以有些翻译可能很不适合中国的语境，有些措辞啥的也不是特别准确。不过假如有能力可以读原版的话，那我肯定建议大家读原版。
